//! Lower ProgramIr into inspectable Rust that reconstructs and evaluates IR.

use rite_sem::{BinaryOpIr, EffectKind, ExprIr, KeyIr, ProgramIr, UnaryOpIr, ValueLiteral};
use std::path::Path;

/// Generate `generated.rs` that embeds IR as JSON and evaluates it.
pub fn generate_from_ir(ir: &ProgramIr, source_path: &Path) -> Result<String, String> {
    let ir_json = serde_json::to_string(ir).map_err(|e| e.to_string())?;
    // Escape for raw string — use base64 to avoid quote issues
    let b64 = base64_encode(ir_json.as_bytes());

    let mut out = String::new();
    out.push_str("//! Generated by rite-compiler from IR (not source re-embed).\n");
    out.push_str(&format!("// rite: {}\n", source_path.display()));
    out.push_str("// Source map: IR node spans retained inside embedded ProgramIr JSON.\n\n");
    // A generated crate is built with whatever RUSTFLAGS the user has, and `-Dwarnings` is
    // common enough that a lint here must not be able to fail their build — the author of a
    // Rite script cannot act on a warning in machine-written Rust.
    //
    // Each of these is something lowering produces by construction: `Key` is imported
    // whether or not a record is built; `^` lowers to a `return`, so the assignment after
    // it in the enclosing block is unreachable; and a compiled function is dead code when
    // every call to it sits inside a statement that fell back to the interpreter.
    out.push_str(
        "#![allow(unused_imports, unused_mut, unused_variables, dead_code, \
         unreachable_code, unused_parens, unused_braces, clippy::all)]\n",
    );
    out.push_str("use rite_runtime::{Key, RuntimeContext, Value, EvalError};\n");

    out.push_str("use rite_sem::ProgramIr;\n\n");

    out.push_str("fn embedded_ir() -> ProgramIr {\n");
    out.push_str(&format!("    let b64 = r#\"{}\"#;\n", b64));
    out.push_str("    let bytes = decode_b64(b64);\n");
    out.push_str("    let json = String::from_utf8(bytes).expect(\"utf8 ir\");\n");
    out.push_str("    serde_json::from_str(&json).expect(\"parse ir\")\n");
    out.push_str("}\n\n");

    out.push_str("fn decode_b64(s: &str) -> Vec<u8> {\n");
    out.push_str("    // minimal base64 decode\n");
    out.push_str(BASE64_DECODE_FN);
    out.push_str("}\n\n");

    // Lower each top-level statement to Rust, falling back per statement to the
    // interpreter for anything the backend cannot express yet. The embedded IR stays
    // because functions are registered from it and the fallback evaluates against it.
    let statements = ir
        .modules
        .first()
        .map(|m| m.statements.as_slice())
        .unwrap_or(&[]);
    let mut lowered = 0usize;
    let mut fell_back: Vec<&'static str> = Vec::new();

    // Emit the function bodies first. This is where a program spends its time — with only
    // top-level statements compiled, a `fib(24)` binary ran in exactly the interpreter's
    // 778ms, because the call was compiled and the body it called was not.
    let (compiled, fn_fallbacks) = crate::lower::survey(ir);
    let mut bodies = String::new();
    for f in &ir.functions {
        if let Ok(code) = crate::lower::function(f, &compiled) {
            bodies.push_str(&code);
            bodies.push('\n');
        }
    }

    out.push_str(
        "pub async fn rite_main(ctx: &mut RuntimeContext) -> Result<Value, EvalError> {\n",
    );
    out.push_str("    let __ir = embedded_ir();\n");
    // Without this a call resolves nothing and a recursive function reports `undefined
    // name` instead of recursing.
    out.push_str("    rite_runtime::register_functions(&__ir, ctx);\n");
    out.push_str(
        "    let __stmts = __ir.modules.first().map(|m| m.statements.as_slice()).unwrap_or(&[]);\n",
    );
    out.push_str("    let mut __last = Value::None;\n");
    out.push_str("    let __r: Result<Value, EvalError> = async {\n");
    for (i, stmt) in statements.iter().enumerate() {
        match crate::lower::expr(stmt, &compiled) {
            Ok(code) => {
                lowered += 1;
                out.push_str(&format!("        __last = {};\n", code));
            }
            Err(crate::lower::Unsupported(why)) => {
                fell_back.push(why);
                out.push_str(&format!(
                    "        __last = {{ let mut __ev = rite_runtime::Evaluator::new(ctx); \
                     __ev.eval_expr(&__stmts[{i}]).await? }}; // fallback: {why}\n"
                ));
            }
        }
    }
    out.push_str("        Ok(__last)\n    }.await;\n");
    // A `^` at the top level is the script's value, not an error.
    out.push_str(
        "    let __value = match __r {\n\
         \x20       Err(EvalError::Return(v)) => v,\n\
         \x20       Err(e) => return Err(e),\n\
         \x20       Ok(v) => v,\n\
         \x20   };\n",
    );
    // The interpreter calls `main` after the top-level statements when the program
    // declares one (see `EntryPoint::Main` in rite-runtime's IR evaluator). The
    // generated code ran the top level and stopped, so every `◆! main()` script —
    // which is how the book writes almost all of them — compiled to a binary that
    // did nothing and exited 0. Nothing caught it because conformance fixtures are
    // written as top-level statements, where the two paths did agree.
    //
    // Dispatched through the registry rather than calling the generated
    // `rite_fn_main` directly, so a `main` the backend could not lower still runs
    // via the interpreter fallback, exactly as its callers already do.
    out.push_str(
        "    if matches!(__ir.entry, rite_sem::EntryPoint::Main { .. }) {\n\
         \x20       let __main = rite_runtime::lookup_global(ctx, \"main\")?;\n\
         \x20       let mut __ev = rite_runtime::Evaluator::new(ctx);\n\
         \x20       return __ev.call_value_public(__main, vec![Value::list(Vec::<Value>::new())]).await;\n\
         \x20   }\n",
    );
    out.push_str("    Ok(__value)\n");
    out.push_str("}\n\n");

    // Closure bodies hoisted during lowering, then the compiled functions. Emitted after
    // `rite_main` because lowering the statements is what discovers them.
    for code in compiled.take_hoisted() {
        out.push_str(&code);
        out.push('\n');
    }
    out.push_str(&bodies);

    out.push_str(&format!(
        "// backend: {} of {} top-level statements and {} of {} functions lowered to Rust\n",
        lowered,
        statements.len(),
        compiled.len(),
        ir.functions.len()
    ));
    for (name, why) in &fn_fallbacks {
        out.push_str(&format!("// interpreted function `{}`: {}\n", name, why));
    }
    if !fell_back.is_empty() {
        let mut kinds: Vec<&str> = fell_back.clone();
        kinds.sort_unstable();
        kinds.dedup();
        out.push_str(&format!(
            "// interpreted fallback for: {}\n\n",
            kinds.join(", ")
        ));
    }

    // Also emit a human-readable IR summary with source map comments
    out.push_str("/* IR summary (inspectable)\n");
    out.push_str(&format!(" modules: {}\n", ir.modules.len()));
    out.push_str(&format!(" functions: {}\n", ir.functions.len()));
    for f in &ir.functions {
        out.push_str(&format!(" // rite: fn {} span {:?}\n", f.name, f.span));
    }
    if let Some(m) = ir.modules.first() {
        for (i, stmt) in m.statements.iter().enumerate() {
            out.push_str(&format!(" // rite: stmt[{}] span {:?}\n", i, stmt.span()));
            let _ = emit_expr_comment(&mut out, stmt, 1);
        }
    }
    out.push_str("*/\n");

    // Ensure types used
    let _ = (
        ExprIr::Constant(ValueLiteral::None(rite_core::Span::DUMMY)),
        BinaryOpIr::Add,
        UnaryOpIr::Neg,
        EffectKind::Pure,
        KeyIr::Ident(String::new()),
    );

    Ok(out)
}

fn emit_expr_comment(out: &mut String, expr: &ExprIr, depth: usize) -> Result<(), ()> {
    let pad = "  ".repeat(depth);
    match expr {
        ExprIr::Constant(v) => out.push_str(&format!("{}// const {:?}\n", pad, v.span())),
        ExprIr::Binary {
            left,
            right,
            op,
            span,
        } => {
            out.push_str(&format!("{}// binary {:?} @ {:?}\n", pad, op, span));
            let _ = emit_expr_comment(out, left, depth + 1);
            let _ = emit_expr_comment(out, right, depth + 1);
        }
        ExprIr::NativeCall { name, span, .. } => {
            out.push_str(&format!("{}// native {} @ {:?}\n", pad, name, span));
        }
        ExprIr::CapabilityCall { path, span, .. } => {
            out.push_str(&format!("{}// cap @{} @ {:?}\n", pad, path.join("."), span));
        }
        ExprIr::Pipeline { span, .. } => {
            out.push_str(&format!("{}// pipeline @ {:?}\n", pad, span));
        }
        ExprIr::Call { span, .. } => {
            out.push_str(&format!("{}// call @ {:?}\n", pad, span));
        }
        other => {
            out.push_str(&format!("{}// expr @ {:?}\n", pad, other.span()));
        }
    }
    Ok(())
}

fn base64_encode(data: &[u8]) -> String {
    const T: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::new();
    for chunk in data.chunks(3) {
        let b0 = chunk[0] as u32;
        let b1 = chunk.get(1).copied().unwrap_or(0) as u32;
        let b2 = chunk.get(2).copied().unwrap_or(0) as u32;
        let n = (b0 << 16) | (b1 << 8) | b2;
        out.push(T[((n >> 18) & 63) as usize] as char);
        out.push(T[((n >> 12) & 63) as usize] as char);
        if chunk.len() > 1 {
            out.push(T[((n >> 6) & 63) as usize] as char);
        } else {
            out.push('=');
        }
        if chunk.len() > 2 {
            out.push(T[(n & 63) as usize] as char);
        } else {
            out.push('=');
        }
    }
    out
}

const BASE64_DECODE_FN: &str = r#"
    fn val(c: u8) -> u8 {
        match c {
            b'A'..=b'Z' => c - b'A',
            b'a'..=b'z' => c - b'a' + 26,
            b'0'..=b'9' => c - b'0' + 52,
            b'+' => 62,
            b'/' => 63,
            _ => 0,
        }
    }
    let s = s.as_bytes();
    let mut out = Vec::new();
    let mut i = 0;
    while i + 3 < s.len() {
        let n = ((val(s[i]) as u32) << 18)
            | ((val(s[i + 1]) as u32) << 12)
            | ((val(s[i + 2]) as u32) << 6)
            | (val(s[i + 3]) as u32);
        out.push(((n >> 16) & 0xff) as u8);
        if s[i + 2] != b'=' {
            out.push(((n >> 8) & 0xff) as u8);
        }
        if s[i + 3] != b'=' {
            out.push((n & 0xff) as u8);
        }
        i += 4;
    }
    out
"#;
