//! Lower ProgramIr into inspectable Rust that reconstructs and evaluates IR.

use rite_sem::{ProgramIr, ExprIr, ValueLiteral, BinaryOpIr, UnaryOpIr, EffectKind, KeyIr};
use std::path::Path;

/// Generate `generated.rs` that embeds IR as JSON and evaluates it.
pub fn generate_from_ir(ir: &ProgramIr, source_path: &Path) -> Result<String, String> {
    let ir_json = serde_json::to_string(ir).map_err(|e| e.to_string())?;
    // Escape for raw string — use base64 to avoid quote issues
    let b64 = base64_encode(ir_json.as_bytes());

    let mut out = String::new();
    out.push_str("//! Generated by rite-compiler from IR (not source re-embed).\n");
    out.push_str(&format!("// rite: {}\n", source_path.display()));
    out.push_str("// Source map: IR node spans retained inside embedded ProgramIr JSON.\n\n");
    out.push_str("use rite_runtime::{run_ir, RuntimeContext, Value, EvalError};\n");
    out.push_str("use rite_sem::ProgramIr;\n\n");

    out.push_str("fn embedded_ir() -> ProgramIr {\n");
    out.push_str(&format!("    let b64 = r#\"{}\"#;\n", b64));
    out.push_str("    let bytes = decode_b64(b64);\n");
    out.push_str("    let json = String::from_utf8(bytes).expect(\"utf8 ir\");\n");
    out.push_str("    serde_json::from_str(&json).expect(\"parse ir\")\n");
    out.push_str("}\n\n");

    out.push_str("fn decode_b64(s: &str) -> Vec<u8> {\n");
    out.push_str("    // minimal base64 decode\n");
    out.push_str(BASE64_DECODE_FN);
    out.push_str("}\n\n");

    out.push_str("pub async fn rite_main(ctx: &mut RuntimeContext) -> Result<Value, EvalError> {\n");
    out.push_str("    let ir = embedded_ir();\n");
    out.push_str("    run_ir(&ir, ctx).await\n");
    out.push_str("}\n\n");

    // Also emit a human-readable IR summary with source map comments
    out.push_str("/* IR summary (inspectable)\n");
    out.push_str(&format!(" modules: {}\n", ir.modules.len()));
    out.push_str(&format!(" functions: {}\n", ir.functions.len()));
    for f in &ir.functions {
        out.push_str(&format!(
            " // rite: fn {} span {:?}\n",
            f.name, f.span
        ));
    }
    if let Some(m) = ir.modules.first() {
        for (i, stmt) in m.statements.iter().enumerate() {
            out.push_str(&format!(
                " // rite: stmt[{}] span {:?}\n",
                i,
                stmt.span()
            ));
            let _ = emit_expr_comment(&mut out, stmt, 1);
        }
    }
    out.push_str("*/\n");

    // Ensure types used
    let _ = (
        ExprIr::Constant(ValueLiteral::None(rite_core::Span::DUMMY)),
        BinaryOpIr::Add,
        UnaryOpIr::Neg,
        EffectKind::Pure,
        KeyIr::Ident(String::new()),
    );

    Ok(out)
}

fn emit_expr_comment(out: &mut String, expr: &ExprIr, depth: usize) -> Result<(), ()> {
    let pad = "  ".repeat(depth);
    match expr {
        ExprIr::Constant(v) => out.push_str(&format!("{}// const {:?}\n", pad, v.span())),
        ExprIr::Binary { left, right, op, span } => {
            out.push_str(&format!("{}// binary {:?} @ {:?}\n", pad, op, span));
            let _ = emit_expr_comment(out, left, depth + 1);
            let _ = emit_expr_comment(out, right, depth + 1);
        }
        ExprIr::NativeCall { name, span, .. } => {
            out.push_str(&format!("{}// native {} @ {:?}\n", pad, name, span));
        }
        ExprIr::CapabilityCall { path, span, .. } => {
            out.push_str(&format!("{}// cap @{} @ {:?}\n", pad, path.join("."), span));
        }
        ExprIr::Pipeline { span, .. } => {
            out.push_str(&format!("{}// pipeline @ {:?}\n", pad, span));
        }
        ExprIr::Call { span, .. } => {
            out.push_str(&format!("{}// call @ {:?}\n", pad, span));
        }
        other => {
            out.push_str(&format!("{}// expr @ {:?}\n", pad, other.span()));
        }
    }
    Ok(())
}

fn base64_encode(data: &[u8]) -> String {
    const T: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::new();
    for chunk in data.chunks(3) {
        let b0 = chunk[0] as u32;
        let b1 = chunk.get(1).copied().unwrap_or(0) as u32;
        let b2 = chunk.get(2).copied().unwrap_or(0) as u32;
        let n = (b0 << 16) | (b1 << 8) | b2;
        out.push(T[((n >> 18) & 63) as usize] as char);
        out.push(T[((n >> 12) & 63) as usize] as char);
        if chunk.len() > 1 {
            out.push(T[((n >> 6) & 63) as usize] as char);
        } else {
            out.push('=');
        }
        if chunk.len() > 2 {
            out.push(T[(n & 63) as usize] as char);
        } else {
            out.push('=');
        }
    }
    out
}

const BASE64_DECODE_FN: &str = r#"
    fn val(c: u8) -> u8 {
        match c {
            b'A'..=b'Z' => c - b'A',
            b'a'..=b'z' => c - b'a' + 26,
            b'0'..=b'9' => c - b'0' + 52,
            b'+' => 62,
            b'/' => 63,
            _ => 0,
        }
    }
    let s = s.as_bytes();
    let mut out = Vec::new();
    let mut i = 0;
    while i + 3 < s.len() {
        let n = ((val(s[i]) as u32) << 18)
            | ((val(s[i + 1]) as u32) << 12)
            | ((val(s[i + 2]) as u32) << 6)
            | (val(s[i + 3]) as u32);
        out.push(((n >> 16) & 0xff) as u8);
        if s[i + 2] != b'=' {
            out.push(((n >> 8) & 0xff) as u8);
        }
        if s[i + 3] != b'=' {
            out.push((n & 0xff) as u8);
        }
        i += 4;
    }
    out
"#;
