//! Ahead-of-time compilation: IR → Rust → cargo build.

mod codegen;

use rite_caps::PermissionSet;
use rite_core::SourceMap;
use rite_sem::{compile_path, compile_to_ir, ProgramIr};
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};
use std::process::Command;

pub use codegen::generate_from_ir;

pub fn build_script(
    file: &Path,
    release: bool,
    emit_rust: bool,
    output: Option<&Path>,
    perms: &PermissionSet,
) -> Result<PathBuf, String> {
    let text = std::fs::read_to_string(file).map_err(|e| e.to_string())?;
    let (ir, diags, _sources) = compile_path(file);
    if diags.has_errors() {
        return Err(format!("compile errors: {} diagnostics", diags.len()));
    }
    let ir = ir.ok_or_else(|| "no IR".to_string())?;

    let hash = hex::encode(&Sha256::digest(text.as_bytes())[..16]);
    let build_dir = PathBuf::from(".rite/build").join(&hash);
    std::fs::create_dir_all(build_dir.join("src")).map_err(|e| e.to_string())?;

    let generated = generate_from_ir(&ir, file)?;
    let main_rs = format!(
        r#"//! Generated by rite build from {}
// rite-compiler version {}
// Artifact: embedded ProgramIr (JSON/base64), evaluated via run_ir for parity.

mod generated;
mod source_map;

use rite_runtime::{{RuntimeContext, Value}};
use rite_caps::{{install_defaults, PermissionSet}};

#[tokio::main]
async fn main() {{
    let mut ctx = RuntimeContext::new();
    let perms = PermissionSet::allow_all();
    install_defaults(&mut ctx, perms);
    match generated::rite_main(&mut ctx).await {{
        Ok(v) => {{
            for line in &ctx.stdout {{
                print!("{{}}", line);
            }}
            if !matches!(v, Value::None) && ctx.stdout.is_empty() {{
                println!("{{}}", v.to_display(&ctx.atoms));
            }}
        }}
        Err(e) => {{
            eprintln!("runtime error: {{}}", e);
            std::process::exit(1);
        }}
    }}
}}
"#,
        file.display(),
        env!("CARGO_PKG_VERSION")
    );

    std::fs::write(build_dir.join("src/main.rs"), main_rs).map_err(|e| e.to_string())?;
    std::fs::write(build_dir.join("src/generated.rs"), &generated).map_err(|e| e.to_string())?;
    std::fs::write(
        build_dir.join("src/source_map.rs"),
        "// Source spans live inside embedded ProgramIr JSON.\n// rustc errors that reference generated.rs:line map to IR summary comments.\n",
    )
    .map_err(|e| e.to_string())?;

    // Also write raw IR for inspection
    std::fs::write(
        build_dir.join("program.ir.json"),
        serde_json::to_string_pretty(&ir).map_err(|e| e.to_string())?,
    )
    .map_err(|e| e.to_string())?;

    let workspace_root = find_workspace_root().unwrap_or_else(|| PathBuf::from("."));
    let cargo_toml = format!(
        r#"[workspace]

[package]
name = "rite_script_{hash}"
version = "0.1.0"
edition = "2021"

[dependencies]
rite-runtime = {{ path = "{rt}" }}
rite-caps = {{ path = "{caps}" }}
rite-core = {{ path = "{core}" }}
rite-sem = {{ path = "{sem}" }}
rite-syntax = {{ path = "{syntax}" }}
tokio = {{ version = "1", features = ["full"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
indexmap = {{ version = "2", features = ["serde"] }}
im = "15"
async-trait = "0.1"
parking_lot = "0.12"
thiserror = "2"
uuid = {{ version = "1", features = ["v4"] }}
chrono = {{ version = "0.4", features = ["serde"] }}
glob = "0.3"
rand = "0.8"
rand_chacha = "0.3"
axum = "0.8"
tower = "0.5"
tower-http = {{ version = "0.6", features = ["trace", "limit", "timeout"] }}
bytes = "1"
futures = "0.3"
tracing = "0.1"
regex = "1"
walkdir = "2"
ctrlc = "3"
"#,
        hash = hash,
        rt = workspace_root.join("crates/rite-runtime").display(),
        caps = workspace_root.join("crates/rite-caps").display(),
        core = workspace_root.join("crates/rite-core").display(),
        sem = workspace_root.join("crates/rite-sem").display(),
        syntax = workspace_root.join("crates/rite-syntax").display(),
    );
    std::fs::write(build_dir.join("Cargo.toml"), cargo_toml).map_err(|e| e.to_string())?;

    let manifest = serde_json::json!({
        "rite_version": env!("CARGO_PKG_VERSION"),
        "source": file.display().to_string(),
        "source_hash": hash,
        "allow_all": perms.allow_all,
        "backend": "ir-json-embed",
    });
    std::fs::write(
        build_dir.join("rite-manifest.json"),
        serde_json::to_string_pretty(&manifest).unwrap(),
    )
    .map_err(|e| e.to_string())?;

    if emit_rust {
        println!("emitted rust + IR in {}", build_dir.display());
    }

    let mut cmd = Command::new("cargo");
    cmd.arg("build")
        .current_dir(&build_dir)
        .arg("--message-format=short");
    if release {
        cmd.arg("--release");
    }
    let status = cmd.status().map_err(|e| e.to_string())?;
    if !status.success() {
        return Err("cargo build failed".into());
    }

    let profile = if release { "release" } else { "debug" };
    let bin_name = format!("rite_script_{}", hash);
    let built = build_dir.join("target").join(profile).join(&bin_name);
    if let Some(out) = output {
        if let Some(parent) = out.parent() {
            std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
        }
        std::fs::copy(&built, out).map_err(|e| e.to_string())?;
        Ok(out.to_path_buf())
    } else {
        Ok(built)
    }
}

fn find_workspace_root() -> Option<PathBuf> {
    let mut dir = std::env::current_dir().ok()?;
    loop {
        if dir.join("Cargo.toml").exists() && dir.join("crates").exists() {
            return Some(dir);
        }
        if !dir.pop() {
            break;
        }
    }
    None
}

/// Differential helper: run IR in-process (same as compiled path).
pub async fn run_ir_mode(file: &Path, perms: PermissionSet) -> Result<rite_runtime::Value, String> {
    let (ir, diags, _) = compile_path(file);
    if diags.has_errors() {
        return Err(format!("compile errors: {}", diags.len()));
    }
    let ir = ir.ok_or_else(|| "no IR".to_string())?;
    let mut ctx = rite_runtime::RuntimeContext::new();
    rite_caps::install_defaults(&mut ctx, perms);
    if let Some(parent) = file.parent() {
        ctx.script_dir = Some(parent.to_path_buf());
    }
    rite_runtime::run_ir(&ir, &mut ctx)
        .await
        .map_err(|e| e.to_string())
}

/// Interpreted mode for differential tests.
pub async fn run_interpreted(
    file: &Path,
    perms: PermissionSet,
) -> Result<(rite_runtime::Value, String, String), String> {
    let mut ctx = rite_runtime::RuntimeContext::new();
    rite_caps::install_defaults(&mut ctx, perms);
    if let Some(parent) = file.parent() {
        ctx.script_dir = Some(parent.to_path_buf());
        ctx.module_roots.push(parent.to_path_buf());
    }
    let mut sources = SourceMap::new();
    let id = sources.add_path(file).map_err(|e| e.to_string())?;
    let sf = sources.get(id).unwrap().clone();
    ctx.sources = sources;
    let v = rite_runtime::run_file(&sf, &mut ctx)
        .await
        .map_err(|e| e.to_string())?;
    Ok((v, ctx.stdout.join(""), ctx.stderr.join("")))
}

// re-export for older call sites
pub fn generate_rust(ir: &ProgramIr, source: &Path, _perms: &PermissionSet) -> String {
    generate_from_ir(ir, source).unwrap_or_default()
}

#[allow(dead_code)]
fn _compile_to_ir_use() {
    let _ = compile_to_ir;
}
