//! Rite runtime: values, environment, async tree-walking evaluator.

pub mod atom;
pub mod budget;
pub mod builtins;
pub mod env;
pub mod eval;
pub mod ops;
pub mod patterns;
pub mod value;

pub use atom::AtomInterner;
pub use budget::ExecutionBudget;
pub use env::Environment;
pub use eval::{
    CapabilityHost, EvalError, Evaluator, FunctionEntry, HttpNextInvoker, OutputSink, OutputStream,
    PendingHttpServer, RuntimeContext, StackFrame,
};
pub use value::*;

use rite_core::{Diagnostics, SourceFile, SourceMap};
use rite_sem::{compile_to_ir, ProgramIr};

/// Run a source file through parse → IR → evaluate.
pub async fn run_source(
    name: &str,
    text: &str,
    ctx: &mut RuntimeContext,
) -> Result<Value, EvalError> {
    let mut sources = SourceMap::new();
    let id = sources.add_file(name, text);
    let file = sources.get(id).unwrap().clone();
    run_file(&file, ctx).await
}

pub async fn run_file(file: &SourceFile, ctx: &mut RuntimeContext) -> Result<Value, EvalError> {
    let path = file.path.clone();
    let roots = ctx.module_roots.clone();
    let (ir, diags) = if let Some(ref p) = path {
        rite_sem::compile_to_ir_with_roots(file, Some(p), &roots)
    } else if let Some(ref dir) = ctx.script_dir {
        rite_sem::compile_to_ir_with_roots(file, None, std::slice::from_ref(dir))
    } else {
        compile_to_ir(file)
    };
    if diags.has_errors() {
        return Err(EvalError::Compile(diags));
    }
    let ir = ir.ok_or_else(|| EvalError::Message("no IR produced".into()))?;
    // Preserve existing sources; ensure entry present for stack traces
    if ctx.sources.files().is_empty() {
        let _ = ctx.sources.add_file(&file.name, file.as_str());
    }
    eval_program(&ir, ctx).await
}

/// Evaluate a pre-built ProgramIr (used by compiled binaries and differential tests).
/// Resolve a bare name the way the interpreter does.
///
/// Three tiers, and the order is the semantics: an environment binding wins, then a
/// registered function, then a builtin — as a dispatch token rather than a value, which is
/// what makes builtins shadowable by a local of the same name.
///
/// Public because generated code has to agree. A backend that only checked the environment
/// would report `undefined name \`str\`` for every builtin used as a value, which is
/// exactly what the first version of the lowering did.
pub fn lookup_global(ctx: &RuntimeContext, name: &str) -> Result<Value, EvalError> {
    if let Some(v) = ctx.env.get(name) {
        return Ok(v);
    }
    if ctx.functions.contains_key(name) {
        return ctx
            .env
            .get(name)
            .ok_or_else(|| EvalError::Message(format!("undefined function {}", name)));
    }
    if crate::eval::is_runtime_builtin(name) {
        return Ok(Value::NativeName(name.to_string()));
    }
    Err(EvalError::Message(format!("undefined name `{}`", name)))
}

/// Make a program's top-level functions callable in `ctx`.
///
/// Registers each one under its name and binds it as a closure value, so a body can reach
/// its siblings and every top-level binding whichever order they appear in — and so a
/// function can recurse.
///
/// Public because code generated by `rite build` needs it before running anything: a
/// lowered call, and the interpreted fallback for a function the backend could not lower,
/// both resolve callees through this. Skipping it produces `undefined name` at runtime for
/// the first recursive function, which is a confusing way to learn it.
pub fn register_functions(ir: &ProgramIr, ctx: &mut RuntimeContext) {
    use crate::value::Closure;
    for f in &ir.functions {
        ctx.functions.insert(
            f.name.clone(),
            crate::eval::FunctionEntry {
                params: f.param_names.clone(),
                body: f.body.clone(),
            },
        );
        // The capture is the module scope itself (shared frames), so ordering does not
        // matter and recursion resolves.
        let clos = Value::Function(Closure {
            id: crate::eval::next_closure_id(),
            name: Some(f.name.clone()),
            params: f.param_names.clone(),
            env: std::sync::Arc::new(parking_lot::RwLock::new(ctx.env.clone())),
            body: f.body.clone(),
        });
        ctx.env.define_name(&f.name, clos, false);
    }
}

pub async fn run_ir(ir: &ProgramIr, ctx: &mut RuntimeContext) -> Result<Value, EvalError> {
    eval_program(ir, ctx).await
}

pub async fn eval_program(ir: &ProgramIr, ctx: &mut RuntimeContext) -> Result<Value, EvalError> {
    let mut evaluator = Evaluator::new(ctx);
    evaluator.eval_program(ir).await
}

pub fn check_source(name: &str, text: &str) -> Diagnostics {
    let mut sources = SourceMap::new();
    let id = sources.add_file(name, text);
    let file = sources.get(id).unwrap().clone();
    let (_ir, diags) = compile_to_ir(&file);
    diags
}
