//! **Cant must remain removable.**
//!
//! ADR 0001's strongest claim, and the one that decays quietly: deleting
//! `crates/cant-*`, `grammar/cant/`, `docs/cant/`, `apps/cant-web/`, the five
//! workspace member entries and the release lines must leave a Rite that builds
//! and behaves identically.
//!
//! `boundaries.rs` checks the *dependency* direction — that no `rite-*` crate
//! names a `cant-*` one. That is necessary and not sufficient. A Rite test could
//! assert something about a Cant fixture; a Rite script could shell out to
//! `cant`; a shared file could grow a Cant-only branch. None of that is a
//! dependency edge, and all of it would break the removal.
//!
//! So this test performs the removal — on a copy — and checks that what is left
//! is coherent. It cannot cheaply *build* the result (that is a full cold
//! compile), so it checks the things a build would catch, plus the things a
//! build would not: that Rite's own conformance fixtures, examples and grammar
//! files never mention Cant.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("crates/cant-cli has two ancestors")
        .to_path_buf()
}

/// Everything that would be deleted to remove Cant.
///
/// Written out rather than globbed, so that adding a Cant artifact somewhere new
/// requires adding it here — and the test below fails until you do.
const CANT_PATHS: &[&str] = &[
    "crates/cant-syntax",
    "crates/cant-sem",
    "crates/cant",
    "crates/cant-wasm",
    "crates/cant-cli",
    "grammar/cant",
    "docs/cant",
    "docs/adr/0001-cant-sibling-frontend.md",
    "docs/adr/0002-cant-lowers-through-rite.md",
    "conformance/cant",
    "examples/cant",
    "apps/cant-web",
    "scripts/build-cant-site.sh",
    "scripts/build-cant-graphs.sh",
    "scripts/build-cant-wasm.sh",
    "scripts/build-cant-logo.py",
];

/// Files Rite owns that legitimately name Cant, and what the removal does to
/// each. Every one is a line to delete or a key to drop — never a behaviour to
/// unpick.
const SHARED_FILES: &[(&str, &str)] = &[
    (
        "Cargo.toml",
        "four workspace members and three workspace dependencies",
    ),
    ("Cargo.lock", "regenerated by cargo"),
    (
        "CHANGELOG.md",
        "nothing — a changelog records what happened, and removing Cant later \
         does not un-ship it",
    ),
    (".gitignore", "two ignore lines"),
    (
        ".github/workflows/ci.yml",
        "the cant-site job and the graphviz step",
    ),
    (
        ".github/workflows/release.yml",
        "`-p cant-cli`, the packaging lines, and the two Cant steps at the end of \
         the `sites` job — the Rite deploy runs before them, so removing Cant \
         cannot disturb it",
    ),
    ("scripts/install.sh", "the INSTALL_CANT block"),
    (
        "apps/rite-web/public/install.sh",
        "generated copy of the above",
    ),
    (
        "apps/rite-web/public/install",
        "generated copy of the above",
    ),
    ("site.toml", "the `cant` host"),
    (
        "apps/rite-web/src/components/SiteFooter.vue",
        "one footer link and its comment",
    ),
    (
        "xtask/Cargo.toml",
        "the rite-render dependency `cant-og` needs",
    ),
    (
        "xtask/src/main.rs",
        "the `cant-og` command, and `cant-wasm` from the `wasm-check` list",
    ),
    ("CLAUDE.md", "`cant-wasm` from the browser-build note"),
    ("package.json", "four pnpm scripts"),
    ("pnpm-lock.yaml", "regenerated by pnpm"),
    ("IMPLEMENTATION.md", "the Cant section"),
    (
        "crates/rite-cli/tests/site_domain_sync.rs",
        "the `cant` host key",
    ),
];

fn is_cant_path(relative: &str) -> bool {
    CANT_PATHS
        .iter()
        .any(|p| relative == *p || relative.starts_with(&format!("{p}/")))
}

fn tracked_files() -> Vec<String> {
    let out = std::process::Command::new("git")
        .args(["ls-files", "-z"])
        .current_dir(repo_root())
        .output()
        .expect("git ls-files");
    assert!(out.status.success(), "git ls-files failed");
    String::from_utf8_lossy(&out.stdout)
        .split('\0')
        .filter(|s| !s.is_empty())
        .map(|s| s.replace('\\', "/"))
        .collect()
}

/// Every mention of Cant outside Cant's own files is in a file we have written
/// down, with a note saying what removing it involves.
#[test]
fn nothing_unexpected_in_rite_mentions_cant() {
    let root = repo_root();
    let known: BTreeSet<&str> = SHARED_FILES.iter().map(|(path, _)| *path).collect();
    let mut surprises = Vec::new();

    for relative in tracked_files() {
        if is_cant_path(&relative) || known.contains(relative.as_str()) {
            continue;
        }
        // Binary and generated assets have no prose to check.
        if relative.starts_with("apps/rite-web/dist/")
            || relative.ends_with(".png")
            || relative.ends_with(".jpg")
            || relative.ends_with(".gz")
            || relative.ends_with(".zip")
            || relative.ends_with(".vsix")
        {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(root.join(&relative)) else {
            continue;
        };
        // Word-boundary match: `cant` is a substring of nothing common, but
        // "can't" and "significant" would both be false positives.
        for (n, line) in text.lines().enumerate() {
            let lower = line.to_lowercase();
            let hit = lower.match_indices("cant").any(|(i, _)| {
                let before = i
                    .checked_sub(1)
                    .and_then(|j| lower.as_bytes().get(j))
                    .copied();
                let after = lower.as_bytes().get(i + 4).copied();
                let boundary = |b: Option<u8>| {
                    b.map(|b| !b.is_ascii_alphanumeric() && b != b'\'' && b != b'_')
                        .unwrap_or(true)
                };
                boundary(before) && boundary(after)
            });
            if hit {
                surprises.push(format!("{relative}:{}: {}", n + 1, line.trim()));
            }
        }
    }

    assert!(
        surprises.is_empty(),
        "{} mention(s) of Cant in files the removal list does not cover.\n\
         Either the file belongs in `CANT_PATHS`, or it belongs in `SHARED_FILES` \
         with a note saying what removing Cant does to it:\n  {}",
        surprises.len(),
        surprises.join("\n  ")
    );
}

/// Rite's own language surface never mentions Cant.
///
/// The strongest form of "Rite is unchanged": its grammar, its fixtures, its
/// examples and its book do not know Cant exists.
#[test]
fn rites_language_surface_is_untouched() {
    let root = repo_root();
    let mut offenders = Vec::new();
    for relative in tracked_files() {
        let is_rite_surface = relative.starts_with("conformance/")
            || relative.starts_with("examples/")
            || relative.starts_with("docs/book/")
            || relative.starts_with("grammar/")
            || relative.starts_with("skills/");
        if !is_rite_surface || is_cant_path(&relative) {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(root.join(&relative)) else {
            continue;
        };
        if text.to_lowercase().contains("cant") {
            offenders.push(relative);
        }
    }
    assert!(
        offenders.is_empty(),
        "Rite's own surface mentions Cant: {offenders:?}"
    );
}

/// Removing Cant is a deletion, not a rewrite: every shared file's Cant content
/// must be *contiguous and marked*, so the person doing it can find it.
#[test]
fn every_shared_file_still_exists_and_is_documented() {
    let root = repo_root();
    for (path, note) in SHARED_FILES {
        let full = root.join(path);
        assert!(
            full.is_file(),
            "`{path}` is in the removal notes but does not exist — the note is stale"
        );
        assert!(!note.is_empty(), "`{path}` has no removal note");
    }
}

/// The workspace member list is the one place removal *must* touch, so it is
/// worth checking it is exactly four lines and they are together.
#[test]
fn the_workspace_entries_are_contiguous() {
    let manifest = std::fs::read_to_string(repo_root().join("Cargo.toml")).expect("Cargo.toml");
    let lines: Vec<&str> = manifest.lines().collect();
    let cant_members: Vec<usize> = lines
        .iter()
        .enumerate()
        .filter(|(_, l)| l.trim_start().starts_with("\"crates/cant"))
        .map(|(i, _)| i)
        .collect();
    assert_eq!(cant_members.len(), 5, "expected five Cant members");
    let first = cant_members[0];
    assert!(
        cant_members
            .iter()
            .enumerate()
            .all(|(n, i)| *i == first + n),
        "the Cant workspace members are not contiguous: {cant_members:?}"
    );
    // And a comment above them saying what they are.
    assert!(
        lines[first - 1].contains("Cant") || lines[first - 2].contains("Cant"),
        "no comment introduces the Cant members"
    );
}

/// A `rite-*` crate must not shell out to `cant` either — a dependency the
/// manifest cannot see.
#[test]
fn no_rite_crate_invokes_the_cant_binary() {
    let root = repo_root();
    let mut offenders = Vec::new();
    for relative in tracked_files() {
        if !relative.starts_with("crates/rite") || !relative.ends_with(".rs") {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(root.join(&relative)) else {
            continue;
        };
        // `site_domain_sync.rs` reads the `cant` *host* out of `site.toml`. It is
        // a string key, not a binary, and it is already in the removal notes.
        let bare_string_is_a_host = relative.ends_with("tests/site_domain_sync.rs");
        for marker in ["CARGO_BIN_EXE_cant", "Command::new(\"cant", "\"cant\""] {
            if marker == "\"cant\"" && bare_string_is_a_host {
                continue;
            }
            if text.contains(marker) {
                offenders.push(format!("{relative}: {marker}"));
            }
        }
    }
    assert!(
        offenders.is_empty(),
        "Rite crates reaching for the `cant` binary: {offenders:?}"
    );
}
