//! **Cant must remain removable.**
//!
//! ADR 0001's strongest claim, and the one that decays quietly: deleting
//! `crates/cant-*`, `grammar/cant/`, `docs/cant/`, `apps/cant-web/`, the seven
//! workspace member entries and the release lines must leave a Rite that builds
//! and behaves identically.
//!
//! `boundaries.rs` checks the *dependency* direction — that no `rite-*` crate
//! names a `cant-*` one. That is necessary and not sufficient. A Rite test could
//! assert something about a Cant fixture; a Rite script could shell out to
//! `cant`; a shared file could grow a Cant-only branch. None of that is a
//! dependency edge, and all of it would break the removal.
//!
//! So this test performs the removal — on a copy — and checks that what is left
//! is coherent. It cannot cheaply *build* the result (that is a full cold
//! compile), so it checks the things a build would catch, plus the things a
//! build would not: that Rite's own conformance fixtures, examples and grammar
//! files never mention Cant.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("crates/cant-cli has two ancestors")
        .to_path_buf()
}

/// Everything that would be deleted to remove Cant.
///
/// Written out rather than globbed, so that adding a Cant artifact somewhere new
/// requires adding it here — and the test below fails until you do.
const CANT_PATHS: &[&str] = &[
    "crates/cant-syntax",
    "crates/cant-sem",
    "crates/cant",
    "crates/cant-wasm",
    // Classifies Cant source for colouring, so it has no purpose without Cant.
    // The palette and the terminal escapes it draws on live in `rite-render`,
    // which survives.
    "crates/cant-render",
    // Sigil's browser binding parses Cant source, so it cannot outlive Cant. The
    // *renderer* (`crates/rite-sigil`) can, and does.
    "crates/cant-sigil-wasm",
    "crates/cant-cli",
    "grammar/cant",
    "docs/cant",
    "docs/adr/0001-cant-sibling-frontend.md",
    "docs/adr/0002-cant-lowers-through-rite.md",
    "conformance/cant",
    "examples/cant",
    // Sigil's examples are Cant programs and its scene fixtures are generated
    // from them. The *renderer* survives Cant's removal; these do not.
    "examples/sigil",
    "fixtures/sigil",
    "apps/cant-web",
    // Sigil's site renders Cant programs and has no other producer, so it goes
    // with Cant — as does the WASM binding it loads and the scripts that build
    // them. The *renderer* (`crates/rite-sigil`) survives, which is the boundary
    // that carries the architecture.
    "apps/sigil-web",
    "scripts/build-sigil-wasm.sh",
    "scripts/build-sigil-site.sh",
    "scripts/check-sigil-wasm-parity.mjs",
    "scripts/build-cant-site.sh",
    "scripts/build-cant-graphs.sh",
    "scripts/build-cant-wasm.sh",
    "scripts/build-cant-logo.py",
];

/// Files Rite owns that legitimately name Cant, and what the removal does to
/// each. Every one is a line to delete or a key to drop — never a behaviour to
/// unpick.
const SHARED_FILES: &[(&str, &str)] = &[
    (
        "Cargo.toml",
        "seven workspace members and their workspace dependencies",
    ),
    ("Cargo.lock", "regenerated by cargo"),
    (
        "CHANGELOG.md",
        "nothing — a changelog records what happened, and removing Cant later \
         does not un-ship it",
    ),
    (".gitignore", "two ignore lines"),
    (
        ".github/workflows/ci.yml",
        "the cant-site job and the graphviz step",
    ),
    (
        ".github/workflows/release.yml",
        "`-p cant-cli`, the packaging lines, and the two Cant steps at the end of \
         the `sites` job — the Rite deploy runs before them, so removing Cant \
         cannot disturb it",
    ),
    // Sigil renders Cant graphs but does not depend on Cant (ADR 0006), so
    // removing Cant leaves the renderer building and its tests passing. What it
    // leaves behind is prose: doc comments and pages that explain the adapter
    // boundary by naming the thing on the other side of it.
    (
        "crates/rite-sigil/Cargo.toml",
        "a comment naming the crates it deliberately does not depend on",
    ),
    (
        "crates/rite-sigil/src/lib.rs",
        "doc-comment prose and one field value in the doctest's JSON",
    ),
    (
        "crates/rite-sigil/src/graph.rs",
        "`SourceLanguage::Cant` and the doc comments explaining why the model is \
         not Cant's",
    ),
    (
        "crates/rite-sigil/src/diagnostic.rs",
        "one doc comment comparing the code namespace to Cant's",
    ),
    (
        "crates/rite-sigil/src/canonical.rs",
        "`SourceLanguage::Cant` in test fixtures",
    ),
    (
        "crates/rite-sigil/src/limits.rs",
        "one doc comment recommending `cant graph` for a graph too large to draw",
    ),
    (
        "crates/rite-sigil/src/svg.rs",
        "one doc comment citing the Cant social card as `svg_to_png`'s first \
         caller; the PNG path itself is Rite's and stays",
    ),
    (
        "crates/rite-sigil/src/validate.rs",
        "one doc comment citing `validate_deserialized`",
    ),
    (
        "crates/rite-sigil/src/analysis.rs",
        "`SourceLanguage::Cant` in test fixtures",
    ),
    (
        "crates/rite-sigil/src/layout.rs",
        "`SourceLanguage::Cant` in test fixtures",
    ),
    (
        "crates/rite-sigil/src/scene.rs",
        "nothing — it names no Cant type",
    ),
    (
        "crates/rite-sigil/tests/boundaries.rs",
        "the Cant half of the forbidden-dependency list, which becomes vacuous",
    ),
    (
        "crates/rite-sigil/tests/performance.rs",
        "`SourceLanguage::Cant` in the generated fixture",
    ),
    (
        "crates/rite-sigil/tests/svg_security.rs",
        "`SourceLanguage::Cant` in the hostile-input fixtures",
    ),
    (
        "crates/rite-sigil/tests/visual.rs",
        "`SourceLanguage::Cant` in the rasterised sample graph",
    ),
    (
        "crates/rite-sigil/tests/fuzz.rs",
        "`SourceLanguage::Cant` in the generated graphs",
    ),
    (
        "docs/sigil/deployment.md",
        "two sentences comparing the Sigil worker to Cant's",
    ),
    (
        "crates/rite-sigil/tests/html_export.rs",
        "`SourceLanguage::Cant` in the hostile-input fixtures",
    ),
    (
        "crates/rite-sigil/src/html.rs",
        "nothing — it names no Cant type",
    ),
    (
        "crates/rite-sigil/src/ornament.rs",
        "nothing — it names no Cant type",
    ),
    (
        "crates/rite-sigil/src/marks.rs",
        "nothing — it names no Cant type",
    ),
    (
        "crates/rite-sigil/src/theme.rs",
        "nothing — it names no Cant type",
    ),
    (
        "docs/sigil/README.md",
        "the pipeline diagram and the Cant references in it",
    ),
    (
        "docs/sigil/graph-contract.md",
        "the `cant.graph` adaptation section",
    ),
    ("docs/sigil/scene.md", "the fixture provenance note"),
    (
        "docs/sigil/checklist.md",
        "the criteria naming `cant sigil`; Sigil's own criteria stand",
    ),
    (
        "docs/sigil/implementation-log.md",
        "nothing — a log records what happened",
    ),
    (
        "docs/sigil/visual-language.md",
        "one sentence naming the Cant pipeline; the visual grammar is the renderer's",
    ),
    (
        "docs/sigil/cli.md",
        "the whole page — it documents `cant sigil`, which is removed with Cant",
    ),
    (
        "docs/sigil/themes.md",
        "nothing — themes belong to the renderer",
    ),
    (
        "docs/sigil/accessibility.md",
        "nothing — the summary and titles belong to the renderer",
    ),
    (
        "docs/sigil/internals.md",
        "the pipeline diagram's Cant stages and the parity-gate paragraph",
    ),
    (
        "docs/adr/0003-sigil-is-a-renderer-not-a-runtime.md",
        "nothing — an accepted ADR records a decision, not a live dependency",
    ),
    (
        "docs/adr/0004-sigil-layout-is-non-semantic.md",
        "nothing, as above",
    ),
    ("docs/adr/0005-one-renderer-in-rust.md", "nothing, as above"),
    (
        "docs/adr/0006-sigil-consumes-a-normalized-graph.md",
        "nothing, as above — though it becomes an ADR about an adapter with one \
         producer left",
    ),
    (
        "docs/adr/0007-veil-and-source-privacy.md",
        "nothing, as above",
    ),
    (
        "docs/adr/0008-graphviz-stays-the-technical-view.md",
        "nothing, as above",
    ),
    (
        "docs/adr/0009-glyph-names-a-token-sigil-names-an-artifact.md",
        "nothing, as above",
    ),
    ("scripts/install.sh", "the INSTALL_CANT block"),
    (
        "apps/rite-web/public/install.sh",
        "generated copy of the above",
    ),
    (
        "apps/rite-web/public/install",
        "generated copy of the above",
    ),
    ("site.toml", "the `cant` host"),
    (
        "xtask/Cargo.toml",
        "the rite-render dependency `cant-og` needs",
    ),
    (
        "xtask/src/main.rs",
        "the `cant-og` and `sigil-og` commands, and `cant-wasm` from the \
         `wasm-check` list",
    ),
    ("CLAUDE.md", "`cant-wasm` from the browser-build note"),
    ("package.json", "four pnpm scripts"),
    ("pnpm-lock.yaml", "regenerated by pnpm"),
    ("IMPLEMENTATION.md", "the Cant section"),
    (
        "crates/rite-cli/tests/site_domain_sync.rs",
        "the `cant` host key",
    ),
];

fn is_cant_path(relative: &str) -> bool {
    CANT_PATHS
        .iter()
        .any(|p| relative == *p || relative.starts_with(&format!("{p}/")))
}

fn tracked_files() -> Vec<String> {
    let out = std::process::Command::new("git")
        .args(["ls-files", "-z"])
        .current_dir(repo_root())
        .output()
        .expect("git ls-files");
    assert!(out.status.success(), "git ls-files failed");
    String::from_utf8_lossy(&out.stdout)
        .split('\0')
        .filter(|s| !s.is_empty())
        .map(|s| s.replace('\\', "/"))
        .collect()
}

/// Every mention of Cant outside Cant's own files is in a file we have written
/// down, with a note saying what removing it involves.
#[test]
fn nothing_unexpected_in_rite_mentions_cant() {
    let root = repo_root();
    let known: BTreeSet<&str> = SHARED_FILES.iter().map(|(path, _)| *path).collect();
    let mut surprises = Vec::new();

    for relative in tracked_files() {
        if is_cant_path(&relative) || known.contains(relative.as_str()) {
            continue;
        }
        // Binary and generated assets have no prose to check.
        if relative.starts_with("apps/rite-web/dist/")
            || relative.ends_with(".png")
            || relative.ends_with(".jpg")
            || relative.ends_with(".gz")
            || relative.ends_with(".zip")
            || relative.ends_with(".vsix")
        {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(root.join(&relative)) else {
            continue;
        };
        // Word-boundary match: `cant` is a substring of nothing common, but
        // "can't" and "significant" would both be false positives.
        for (n, line) in text.lines().enumerate() {
            let lower = line.to_lowercase();
            let hit = lower.match_indices("cant").any(|(i, _)| {
                let before = i
                    .checked_sub(1)
                    .and_then(|j| lower.as_bytes().get(j))
                    .copied();
                let after = lower.as_bytes().get(i + 4).copied();
                let boundary = |b: Option<u8>| {
                    b.map(|b| !b.is_ascii_alphanumeric() && b != b'\'' && b != b'_')
                        .unwrap_or(true)
                };
                boundary(before) && boundary(after)
            });
            if hit {
                surprises.push(format!("{relative}:{}: {}", n + 1, line.trim()));
            }
        }
    }

    assert!(
        surprises.is_empty(),
        "{} mention(s) of Cant in files the removal list does not cover.\n\
         Either the file belongs in `CANT_PATHS`, or it belongs in `SHARED_FILES` \
         with a note saying what removing Cant does to it:\n  {}",
        surprises.len(),
        surprises.join("\n  ")
    );
}

/// Rite's own language surface never mentions Cant.
///
/// The strongest form of "Rite is unchanged": its grammar, its fixtures, its
/// examples and its book do not know Cant exists.
#[test]
fn rites_language_surface_is_untouched() {
    let root = repo_root();
    let mut offenders = Vec::new();
    for relative in tracked_files() {
        let is_rite_surface = relative.starts_with("conformance/")
            || relative.starts_with("examples/")
            || relative.starts_with("docs/book/")
            || relative.starts_with("grammar/")
            || relative.starts_with("skills/");
        if !is_rite_surface || is_cant_path(&relative) {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(root.join(&relative)) else {
            continue;
        };
        if text.to_lowercase().contains("cant") {
            offenders.push(relative);
        }
    }
    assert!(
        offenders.is_empty(),
        "Rite's own surface mentions Cant: {offenders:?}"
    );
}

/// Removing Cant is a deletion, not a rewrite: every shared file's Cant content
/// must be *contiguous and marked*, so the person doing it can find it.
#[test]
fn every_shared_file_still_exists_and_is_documented() {
    let root = repo_root();
    for (path, note) in SHARED_FILES {
        let full = root.join(path);
        assert!(
            full.is_file(),
            "`{path}` is in the removal notes but does not exist — the note is stale"
        );
        assert!(!note.is_empty(), "`{path}` has no removal note");
    }
}

/// The workspace member list is the one place removal *must* touch, so it is
/// worth checking the Cant entries are all there and together.
///
/// Seven now, not four: `cant-wasm`, `cant-sigil-wasm` and `cant-render`
/// joined the original four. `cant-sigil-wasm` is Sigil's browser binding,
/// which parses Cant source and therefore cannot outlive Cant — see its
/// manifest for why it is named `cant-` rather than `rite-`. `cant-render`
/// classifies Cant source for colouring, and is the same shape of thing.
#[test]
fn the_workspace_entries_are_contiguous() {
    let manifest = std::fs::read_to_string(repo_root().join("Cargo.toml")).expect("Cargo.toml");
    let lines: Vec<&str> = manifest.lines().collect();
    let cant_members: Vec<usize> = lines
        .iter()
        .enumerate()
        .filter(|(_, l)| l.trim_start().starts_with("\"crates/cant"))
        .map(|(i, _)| i)
        .collect();
    assert_eq!(cant_members.len(), 7, "expected seven Cant members");
    let first = cant_members[0];
    assert!(
        cant_members
            .iter()
            .enumerate()
            .all(|(n, i)| *i == first + n),
        "the Cant workspace members are not contiguous: {cant_members:?}"
    );
    // And a comment above them saying what they are.
    assert!(
        lines[first - 1].contains("Cant") || lines[first - 2].contains("Cant"),
        "no comment introduces the Cant members"
    );
}

/// A `rite-*` crate must not shell out to `cant` either — a dependency the
/// manifest cannot see.
#[test]
fn no_rite_crate_invokes_the_cant_binary() {
    let root = repo_root();
    let mut offenders = Vec::new();
    for relative in tracked_files() {
        if !relative.starts_with("crates/rite") || !relative.ends_with(".rs") {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(root.join(&relative)) else {
            continue;
        };
        for marker in ["CARGO_BIN_EXE_cant", "Command::new(\"cant"] {
            if text.contains(marker) {
                offenders.push(format!("{relative}: {marker}"));
            }
        }

        // A bare `"cant"` is the backstop for `.arg("cant")` and the like, and
        // on its own it is far too loose. `site_domain_sync.rs` reads the `cant`
        // *host* out of `site.toml`; `rite-sigil` names `cant` as a
        // `SourceLanguage`. Neither is an invocation, and neither would be
        // distinguishable from one by a whole-file search — `site_domain_sync.rs`
        // spawns `git`, so even "does this file spawn anything?" says yes.
        //
        // So the backstop is line-level: a bare `"cant"` counts only where the
        // same line is also building a command. That is a rule rather than a
        // list of exempted file names, which is what this was becoming — and a
        // file-name exception is indistinguishable from an oversight six months
        // later.
        for (n, line) in text.lines().enumerate() {
            if !line.contains("\"cant\"") {
                continue;
            }
            let building_a_command = line.contains("Command")
                || line.contains(".arg(")
                || line.contains(".args(")
                || line.contains("exe");
            if building_a_command {
                offenders.push(format!("{relative}:{}: {}", n + 1, line.trim()));
            }
        }
    }
    assert!(
        offenders.is_empty(),
        "Rite crates reaching for the `cant` binary: {offenders:?}"
    );
}
