#!/usr/bin/env python3
"""Regenerate apps/cant-web/public/brand/logo.svg from Rite's logo.

Cant's mark is Rite's mark struck through with the sigil tilde, so the Rite PNG
is embedded verbatim rather than redrawn. Run this after changing Rite's logo, or
the two marks drift and nobody notices until someone compares the two sites.

    python3 scripts/build-cant-logo.py

No dependencies on purpose: this repository has no image tooling installed, and
acquiring some to composite two shapes would be a poor trade.
"""
import base64
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "apps/rite-web/public/brand/logo.png"
TARGET = ROOT / "apps/cant-web/public/brand/logo.svg"

# The tilde, drawn once and used twice: a dark stroke underneath so the pink one
# stays legible over Rite's cyan line-work, then the pink on top.
TILDE = "M 18 80 C 32 50, 54 52, 64 70 C 74 88, 96 90, 110 60"

TEMPLATE = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" width="128" height="128" role="img" aria-label="Cant">
  <title>Cant</title>
  <!--
    Generated by scripts/build-cant-logo.py — do not edit by hand.

    Cant's mark is Rite's, struck through with the sigil tilde. The base layer is
    apps/rite-web/public/brand/logo.png embedded verbatim, so the two marks
    cannot drift.
  -->
  <image href="data:image/png;base64,{b64}" x="0" y="0" width="128" height="128"/>
  <g fill="none" stroke-linecap="round">
    <path d="{tilde}" stroke="#0b0f14" stroke-opacity="0.85" stroke-width="22"/>
    <path d="{tilde}" stroke="#ff7edb" stroke-width="12"/>
  </g>
</svg>
"""


def main() -> None:
    b64 = base64.b64encode(SOURCE.read_bytes()).decode()
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(TEMPLATE.format(b64=b64, tilde=TILDE))
    print(f"wrote {TARGET.relative_to(ROOT)} ({TARGET.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
