//! Property and fuzz smoke tests (§26.5, §26.6).
//!
//! Everything here generates *hostile or degenerate* input and asserts the same
//! four things: no panic, no non-termination, no invalid numeric output, and no
//! markup escaping into the artifact.
//!
//! `proptest` rather than a coverage-guided fuzzer: the input is structured, so
//! a generator that builds graphs is far more likely to reach the interesting
//! shapes than one mutating bytes, and it runs in CI without a separate
//! toolchain. A real `cargo-fuzz` target over the JSON reader is still worth
//! having and is not here.

use proptest::prelude::*;

use rite_sigil::{
    build_scene, normalize, render_svg, EdgeId, EdgeKind, Geometry, LayoutOptions, NodeId,
    NormalizeOptions, OrnamentLevel, PortRef, SigilEdge, SigilGraph, SigilNode, SigilNodeKind,
    SourceLanguage, SvgOptions, ThemeId,
};

/// Text that has broken a renderer somewhere, plus arbitrary unicode.
fn hostile_text() -> impl Strategy<Value = String> {
    prop_oneof![
        Just(r#"<script>alert(1)</script>"#.to_string()),
        Just(r#"" onload="x"#.to_string()),
        Just("\u{0}\u{1}\u{202e}".to_string()),
        Just("]]>".to_string()),
        Just(String::new()),
        ".{0,60}",
    ]
}

fn node_kind() -> impl Strategy<Value = SigilNodeKind> {
    prop_oneof![
        Just(SigilNodeKind::Source),
        Just(SigilNodeKind::Stage),
        Just(SigilNodeKind::Ward),
        Just(SigilNodeKind::Scatter),
        Just(SigilNodeKind::Collect),
        Just(SigilNodeKind::Fork),
        Just(SigilNodeKind::Orbit),
        Just(SigilNodeKind::Effect),
        Just(SigilNodeKind::Output),
        Just(SigilNodeKind::Literal),
        hostile_text().prop_map(SigilNodeKind::Unknown),
    ]
}

/// A graph of `n` nodes with arbitrary edges between them.
///
/// Edges are generated by *index* and then mapped to identifiers, so they always
/// resolve — the interesting failures are in shape, not in dangling references,
/// and validation already has a test per reference rule.
fn arbitrary_graph() -> impl Strategy<Value = SigilGraph> {
    (1usize..14, any::<bool>()).prop_flat_map(|(count, label_them)| {
        (
            prop::collection::vec(node_kind(), count),
            prop::collection::vec((0..count, 0..count, 0u32..4, 0usize..4), 0..24),
            prop::collection::vec(hostile_text(), count),
        )
            .prop_map(move |(kinds, edges, labels)| {
                let mut g = SigilGraph::new(SourceLanguage::Cant, "n0");
                for (i, kind) in kinds.into_iter().enumerate() {
                    let mut node = SigilNode::new(format!("n{i}"), kind);
                    if label_them {
                        node.label = Some(labels[i].clone());
                        node.short_label = Some(labels[i].clone());
                    }
                    g.nodes.push(node);
                }
                for (i, (from, to, ordinal, kind)) in edges.into_iter().enumerate() {
                    g.edges.push(SigilEdge {
                        id: EdgeId::new(format!("e{i}")),
                        from: PortRef::new(format!("n{from}"), ordinal),
                        to: PortRef::new(format!("n{to}"), 0),
                        ordinal,
                        kind: [
                            EdgeKind::Flow,
                            EdgeKind::Enter,
                            EdgeKind::Join,
                            EdgeKind::Feedback,
                        ][kind],
                        region: None,
                    });
                }
                g.exits.push(NodeId::new(format!("n{}", count - 1)));
                g
            })
    })
}

proptest! {
    #![proptest_config(ProptestConfig { cases: 160, ..ProptestConfig::default() })]

    /// The headline property: nothing in the pipeline panics, whatever arrives.
    ///
    /// Includes graphs validation *rejects* — the point is that rejection is a
    /// diagnostic rather than an abort.
    #[test]
    fn the_pipeline_never_panics(graph in arbitrary_graph()) {
        let Ok(normalized) = normalize(graph, &NormalizeOptions::default()) else {
            return Ok(());
        };
        for ornament in OrnamentLevel::ALL {
            let scene = build_scene(
                &normalized,
                &LayoutOptions { ornament: *ornament, ..LayoutOptions::canonical() },
            );
            for theme in ThemeId::ALL {
                let _ = render_svg(&scene, &SvgOptions { theme: *theme, ..Default::default() });
            }
        }
    }

    /// Every coordinate finite. A `NaN` reaches an SVG attribute as the empty
    /// string and renders as nothing, which reads as a layout bug.
    #[test]
    fn every_scene_coordinate_is_finite(graph in arbitrary_graph()) {
        let Ok(normalized) = normalize(graph, &NormalizeOptions::default()) else {
            return Ok(());
        };
        let scene = build_scene(&normalized, &LayoutOptions::canonical());
        for element in &scene.elements {
            let b = element.bounds;
            prop_assert!([b.x, b.y, b.width, b.height].iter().all(|v| v.is_finite()));
            if let Geometry::Mark { center, size, rotation, .. } = &element.geometry {
                prop_assert!(center.is_finite());
                prop_assert!(size.is_finite() && *size > 0.0);
                prop_assert!(rotation.is_finite());
            }
        }
    }

    /// Determinism, over arbitrary shapes rather than the six fixtures.
    #[test]
    fn rendering_is_deterministic(graph in arbitrary_graph()) {
        let Ok(normalized) = normalize(graph, &NormalizeOptions::default()) else {
            return Ok(());
        };
        let options = LayoutOptions::canonical();
        let a = build_scene(&normalized, &options);
        let b = build_scene(&normalized, &options);
        prop_assert_eq!(
            serde_json::to_string(&a).unwrap_or_default(),
            serde_json::to_string(&b).unwrap_or_default()
        );
    }

    /// ADR 0004, over arbitrary shapes: the ornament level moves nothing
    /// semantic. The fixture-based version of this uses one graph; this one uses
    /// every shape the generator can reach.
    #[test]
    fn ornament_never_moves_semantic_geometry(graph in arbitrary_graph()) {
        let Ok(normalized) = normalize(graph, &NormalizeOptions::default()) else {
            return Ok(());
        };
        let semantic = |level| {
            build_scene(&normalized, &LayoutOptions { ornament: level, ..LayoutOptions::canonical() })
                .elements
                .into_iter()
                .filter(|e| !e.is_ornament())
                .collect::<Vec<_>>()
        };
        prop_assert_eq!(semantic(OrnamentLevel::None), semantic(OrnamentLevel::Maximal));
    }

    /// No markup escapes, whatever a label contains.
    #[test]
    fn no_label_can_inject_markup(graph in arbitrary_graph()) {
        let Ok(normalized) = normalize(graph, &NormalizeOptions::default().with_snippets()) else {
            return Ok(());
        };
        let scene = build_scene(&normalized, &LayoutOptions::canonical());
        for mode in [
            rite_sigil::DisclosureMode::Veiled,
            rite_sigil::DisclosureMode::Revealed,
        ] {
            let svg = render_svg(
                &scene,
                &SvgOptions { disclosure: mode, ..Default::default() },
            )
            .svg;
            prop_assert!(!svg.to_lowercase().contains("<script"));
            // Tags balance: an unescaped `<` in a label would open one that
            // never closes.
            prop_assert_eq!(svg.matches('<').count(), svg.matches('>').count());
            // Every attribute is quoted in pairs.
            for tag in svg.split('<').skip(1).filter_map(|t| t.split('>').next()) {
                prop_assert!(tag.matches('"').count() % 2 == 0, "unbalanced quotes in <{}>", tag);
            }
        }
    }

    /// A veiled render draws no text at all, whatever the labels were.
    #[test]
    fn veiled_never_draws_text(graph in arbitrary_graph()) {
        let Ok(normalized) = normalize(graph, &NormalizeOptions::default().with_snippets()) else {
            return Ok(());
        };
        let scene = build_scene(&normalized, &LayoutOptions::canonical());
        let svg = render_svg(&scene, &SvgOptions::default()).svg;
        prop_assert!(!svg.contains("<text"));
    }

    /// Limits hold: a graph past the cap is refused rather than drawn slowly.
    #[test]
    fn the_node_cap_is_enforced(count in 1usize..40) {
        let mut g = SigilGraph::new(SourceLanguage::Cant, "n0");
        for i in 0..count {
            g.nodes.push(SigilNode::new(format!("n{i}"), SigilNodeKind::Stage));
        }
        g.exits.push(NodeId::new(format!("n{}", count - 1)));
        let mut options = NormalizeOptions::default();
        options.limits.max_nodes = 20;
        options.limits.soft_node_warning = 10;
        let result = normalize(g, &options);
        prop_assert_eq!(result.is_err(), count > 20);
    }
}
